version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - '${API_PORT}:3000'
    command: nodemon index.js
    networks: 
    - local
    links: 
    - db
    volumes:
    - .:/app
  db:
    image: mongo:latest
    ports:
    - 27017:27017
    networks:
    - local
    volumes:
    - dbdata:/data/db
  
volumes:
  dbdata:

networks:
  local:
